### ISSUE TITLE
reloadOnSearch: false results in the router state not being updated

### ISSUE THREAD

**Issue by neilff** [neilff/redux-ui-router#17]
Currently we listen to the `$stateChangeSuccess` event which occurs whenever the route changes. We then fire the `STATE_CHANGE_SUCCESS` action type which updates the router state in redux...

Problems arise when `reloadOnSearch` is set to `false`. When this is set, the `$stateChangeSuccess` event no longer fires when a query parameter is added. 

This breaks our router state in our redux store, so we get around this issue by firing a `STATE_CHANGE_SUCCESS` action type after successful `$state.go` if `reloadOnSearch` is equal to `false`... the problem with this is when manual URL manipulation occurs, these are not picked up and again the router state ends up out of sync.

**Comment by neilff** [comment]
@nateabele Wondering if you have any ideas on how to resolve the above problem? If you need some additional context, I can provide an example.

I've tried toying around with listening to `$locationChangeSuccess` instead of `$stateChangeSuccess`, and then grabbing params from $stateParams but noticed that they aren't available when the first `$locationChangeSuccess` event fires.

**Comment by nateabele** [comment]
> Problems arise when reloadOnSearch is set to false. When this is set, the $stateChangeSuccess event no longer fires when a query parameter is added.

The first thing that comes to mind is that you could decorate `$state` and override `transitionTo()` so that you're able to grab the promise it returns and trigger off of that. Not the cleanest thing ever, but it'll do the job.

> [T]he problem with this is when manual URL manipulation occurs, these are not picked up and again the router state ends up out of sync.

How is the URL being manipulated? Via `$location`? One thing you could try is using `$urlRouter` to manually sync UI Router with the current URL. (I think `sync()` is the method you'd be looking for).

We're working to get 1.0 out the door, which has observable dynamic parameters, which is gonna be way better than `reloadOnSearch` (which IMO is kind of a hack).

**Comment by neilff** [comment]
Awesome, I'll dive back into the code in the morning, thanks for the help, :+1:
