### ISSUE TITLE
Active development/Circular dependency isuse

### ISSUE THREAD

**Issue by madou** [neilff/redux-ui-router#6]
Hi,

Sorry for the the issue being raised, couldn't see an email to contact you with. 

Are you still actively working on the router? Any road map? I'm currently playing around with your WIP and was wondering if you could give me any insight for applying the redux middleware.

When I try to apply it I'm getting a circular dependency error (looks like $http). I'm currently one of my angular projects to use a redux backing for fun, but when it comes to hooking everything together with routing it's becoming problematic.

Also with dispatching route changes, I assume I can just import the 'go' action and dispatch one, yes? Or I'm stuck using your angular action factory?

Oh, also your example is a little bit borked, and can't be run out of the box. It's missing some webpack dependencies.

Cheers,
Michael

**Comment by wbuchwalter** [comment]
Hey Michael!
Regarding your issues, is there somewhere we can see your code? Most importantly redux's store creation, and how you consume redux-ui-router action.

**Comment by madou** [comment]
I don't currently have a checked in version for applying the router middleware, but you can however check what I have checked in:

Repository:

Store creation (add in the middleware to see the error if you'd like):
https://github.com/madou/armory-ng/blob/with-redux/client/src/app/app.redux-store.js

**Comment by madou** [comment]
I don't currently have a checked in version for applying the router middleware, but you can however check what I have checked in (logging redux middleware is turned on):

Repository:
https://github.com/madou/armory-ng/tree/with-redux/

To run:
npm install
bower install
gulp serve

Store creation (add in the router middleware to see the error if you'd like):
https://github.com/madou/armory-ng/blob/with-redux/client/src/app/app.redux-store.js

Root reducer:
https://github.com/madou/armory-ng/blob/with-redux/client/src/app/reducers/index.js

Angular entry point:
https://github.com/madou/armory-ng/blob/with-redux/client/src/app/app.module.js

Not sure if this can help you 100%. I haven't played around with your wip as much as I would have liked, just trying to hack things together as I go. Trying to force myself not to re-write everything in React hehe.

Let me know if you need more info.

Michael

**Comment by wbuchwalter** [comment]
Hey,
Just to be clear i'm not the author of this project :)

Regarding your issue, here is the problem:
ng-redux depends on the middleware you pass it, the router middleware in this case.
The router middleware depends on `$state`, which in turn depends on things that depends on `$http`.
And finally your [http-auth-interceptor](https://github.com/madou/armory-ng/blob/with-redux/client/src/app/interceptors/http-auth-interceptor.js) depends on `ng-redux`.
We can simplify this to: `http-auth-interceptor` depends on `$http`, which is not allowed because this would create a circular dependency.

You can take a look at this [Stackoverflow question](http://stackoverflow.com/questions/25495942/circular-dependency-found-http-templatefactory-view-state) which seems to be exactly your problem.

**Comment by madou** [comment]
Ohh righto. I've run into this before, my mistake. Thanks for having a dig, cheers!

**Comment by wbuchwalter** [comment]
:+1:
